"""init

Revision ID: 11df74401620
Revises: 
Create Date: 2026-03-24 17:07:06.292147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11df74401620'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', sa.String(), server_default=sa.text("'not_paid'"), nullable=False),
    sa.CheckConstraint("payment_status IN ('not_paid', 'partially_paid', 'paid')", name='check_order_payment_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('type', sa.Enum('CASH', 'ACQUIRING', name='paymenttype', native_enum=False), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('bank_payment_id', sa.String(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'success', 'failed', 'refunded')", name='check_order_payment_status'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.drop_table('orders')
    # ### end Alembic commands ###
